make mock registration fatal
This shouldn't ever happen since the mocks are defined by the calling
test framework. Failure should only occur when the function doesn't
exist, in which case it's an application error we don't want to try to
recover from.

diff --git a/apron b/apron
--- a/apron
+++ b/apron
@@ -116,7 +116,10 @@ APRON_register() {
     printf 'APRON: registering mock: %s\n' "$1"
   fi
 
-  APRON_defined_mocks["$1"]=$(declare -f "$1")
+  if ! APRON_defined_mocks["$1"]=$(declare -f "$1"); then
+    printf '==> FATAL: failed to register mock: %s\n' "$1"
+    exit 1
+  fi
   export -f "$1"
 }
 
